spring:
  application:
      name: golf-service-test
  redis:
    host: 127.0.0.1
    port: 6380
    timeout: 20000
    pool:
      maxIdle: 300
      minIdle: 100
      max-active: 200
      max-wait: 20000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/e_wheel_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Techsoon2020a
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 9096
  tomcat:
    basedir: /etc/ewheel_test/data/app/temp


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
      
path:
  appPath: /etc/ewheel_test/data/app/
  firmwarePath: /etc/ewheel_test/data/firmware/
  log: /var/lib/jenkins/workspace/log/

#####################################################################################################
#spring boot health config
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false
#####################################################################################################



