spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    pool:
      maxIdle: 300
      minIdle: 100
      max-active: 200
      max-wait: 20000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/e_wheel?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 9091


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

zuul:
    host:
        connect-timeout-millis: 10000
        socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


#####################################################################################################
#spring boot health config
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false
#####################################################################################################



